<!DOCTYPE html>

<html>
<head>
<title>{{ $title }}</title>
<style>
body { font-family: sans-serif; font-size: 12px; }
.header { text-align: center; margin-bottom: 20px; }
.details { margin-bottom: 20px; }
table { width: 100%; border-collapse: collapse; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
th { background-color: #f2f2f2; font-weight: bold; }
.footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; }
</style>
</head>
<body>
<div class="header">
<h2>{{ strtoupper($title) }}</h2>
<p>Date Generated: {{ $date }}</p>
</div>

<div class="details">
    <strong>Academic Year:</strong> {{ $year }} <br>
    <strong>Class:</strong> {{ $class }} <br>
    <strong>Total Students:</strong> {{ count($students) }}
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Student ID</th>
            <th>Full Name</th>
            <th>Gender</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($students as $index => $student)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $student->student->student_id }}</td>
                <td>{{ $student->student->last_name }}, {{ $student->student->first_name }}</td>
                <td>{{ ucfirst($student->student->gender) }}</td>
                <td>{{ ucfirst($student->status) }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    Generated by School Management System
</div>


</body>
</html>